apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: m0cfehzb6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/m0cfehzb6-java-quarkus-gitops